version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: samlee
      POSTGRES_PASSWORD: sam110306
      POSTGRES_DB: samlee_home_goods
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: samlee
      POSTGRES_PASSWORD: sam110306
      POSTGRES_DB: samlee_home_goods
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle_cache:
  pg_data:
