default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: samlee
  password: sam110306           
  host: localhost


development:
  <<: *default
  database: samlee_home_goods_development


test:
  <<: *default
  database: samlee_home_goods_test


production:
  <<: *default
  database: samlee_home_goods_production
  username: samlee_home_goods
  password: <%= ENV["SAMLEE_HOME_GOODS_DATABASE_PASSWORD"] %>
